### ISSUE TITLE
Build fehler

### ISSUE THREAD

**Issue by Felix-Koch** [gerriet-hinrichs/SE2-Tierheimprojekt#1]
apigenerator
vermutlich falsch in das Projekt eingebunden
(buidpath)

**Comment by gerriet-hinrichs** [comment]
Der Generator wurde im Branch `feature/server-api` gebaut und ist vollständig nach develop gemerged. Da sowohl bei mir, als auch bei Travis CI kein Fehler auftritt, kann ich das nicht reproduzieren.
