### ISSUE TITLE
QuestionDAO -> getFirstQuestion() return all, not only the first

### ISSUE THREAD

**Issue by Felix-Koch** [gerriet-hinrichs/SE2-Tierheimprojekt#10]
Tried to fix with:
@Query("select q from QuestionEntity q where q.sortOrder = min(q.sortOrder)")
QuestionEntity getFirstQuestion();

But it looks like JQA dosnt support min()

**Comment by gerriet-hinrichs** [comment]
Looks fine to me:
`@Query("select q from QuestionEntity q order by q.sortOrder")`
`QuestionEntity getFirstQuestion();`
Where is the problem?

**Comment by Felix-Koch** [comment]
Der @Querry Will eine Liste zurück geben, aber es wird nur ein Onjekt erwartet = Exeption (nur bei Aufruf)

**Comment by gerriet-hinrichs** [comment]
Fixed.
