### ISSUE TITLE
:buildTypescriptForTests fail

### ISSUE THREAD

**Issue by Felix-Koch** [gerriet-hinrichs/SE2-Tierheimprojekt#11]
Execution failed for task ':buildTypescriptForTests'.

src/main/view/clientApi/alias.d.ts(32,63): error TS1023: An index signature parameter type must be 'string' or 'number'.

No idea why now ...

**Comment by gerriet-hinrichs** [comment]
Fixed. Was an error within primitive type detection from service api generator.
