### ISSUE TITLE
org.hibernate.LazyInitializationException

### ISSUE THREAD

**Issue by Felix-Koch** [gerriet-hinrichs/SE2-Tierheimprojekt#12]
org.hibernate.LazyInitializationException at QuestionServiceTest.java:87
QuestionServiceTest.java:87 -> questionService.getFirstWithAnswers() -> 
QuestionService:62             ->return new QuestionModel(questionEntity) ->

QuestionModel construktor can not find AnswerEntities.

**Comment by gerriet-hinrichs** [comment]
Fixed.
