### ISSUE TITLE
getNextforAnswer() DAO/Service if called with last Question

### ISSUE THREAD

**Issue by Felix-Koch** [gerriet-hinrichs/SE2-Tierheimprojekt#13]
QuestionDAO.getNextforAnswer()
Is returning IndexOutOfBoundsException insted of null by rinning it at the Last Question

Temp "fix"
QuestionService.getNextforAnswer()
Catched the IndexOutOfBoundsException and return null

**Comment by gerriet-hinrichs** [comment]
If you would've kept your feature branch up to date you would've noticed that this was already fixed.
