### ISSUE TITLE
QuestionApi$getAnswersForQuestion$...' cannot be converted to type 'question'.

### ISSUE THREAD

**Issue by kboehringer** [gerriet-hinrichs/SE2-Tierheimprojekt#15]
Die neuen Attribute müssen in TS eingefügt werden (ich habe noch nie mit TS gearbeitet). Ist Adrian dafür zuständig?

**Comment by gerriet-hinrichs** [comment]
Fixed mit https://github.com/gerriet-hinrichs/SE2-Tierheimprojekt/commit/e9359a82b327aa47610a2d8c25563ebe240376bc
